### ISSUE TITLE
How to apply for a pan-domain name in the global configuration

### ISSUE THREAD

**Issue by vfiee** [caddy-dns/alidns#4]
my configuration is as follows, but it is wrong
{
   acme_dns {
      access_key_id my_key_id
      access_key_secret my_key_secret
   } 
}

error log:
validate: adapting config using caddyfile: parsing caddyfile tokens for 'acme_dns': ./Caddyfile:4 - Error during parsing: Wrong argument count or unexpected line ending after 'access_key_id'

**Comment by viscropst** [comment]
This [Doc](https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148) will help you.

**Comment by vfiee** [comment]
> This [Doc](https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148) will help you.

Thank you, I have seen the updated content of the document. In fact, I have tried that. There may be other problems. I will try other methods.
